oro_layout:
    actions:
        - @setBlockTheme:
            themes: 'OroCRMMagentoContactUsBundle::MagentoContactForm.html.twig'
        - @setOption:
            id:          embedded_form
            optionName:  preferred_fields
            optionValue: [firstName, lastName, organizationName, preferredContactMethod, phone, emailAddress, contactReason]
        - @setOption:
            id:          embedded_form
            optionName:  groups
            optionValue:
                contact:
                    title:   Contact Information
                    default: true
        - @move:
            id:          embedded_form_submit
            parentId:    embedded_form
            siblingId:   'embedded_form:group_contact'

    conditions:
        @eq:
            - $context.embedded_form_type
            - 'orocrm_magento_contact_us.embedded_form'
